"""Email webhook notifications for workflow findings."""

import logging
from html import escape as html_escape

import httpx

from config import Settings
from models.results import WorkflowResult

logger = logging.getLogger(__name__)


async def send_email_notification(
    workflow_result: WorkflowResult,
    settings: Settings,
) -> bool:
    """Send an email summary of workflow findings via webhook. Returns True if sent successfully."""
    if not settings.email_webhook_url or not settings.email_recipients:
        return False

    total_findings = sum(len(r.findings) for r in workflow_result.agent_results)
    if total_findings == 0:
        return False  # Skip notification if no findings

    # Build HTML email body
    html_body = f"""
    <html>
    <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; line-height: 1.6; color: #333;">
    <h2>📊 Analysis Complete</h2>
    <p><strong>Repository:</strong> {html_escape(workflow_result.repo_name)}</p>
    <p><strong>Branch:</strong> {html_escape(workflow_result.branch)}</p>
    <p><strong>Workflow:</strong> {html_escape(workflow_result.workflow_name)}</p>
    <p><strong>Total Findings:</strong> <span style="font-size: 1.2em; color: #d32f2f;">{total_findings}</span></p>
    <p><strong>Duration:</strong> {(workflow_result.completed_at - workflow_result.started_at).total_seconds():.1f}s</p>

    <h3>Findings by Agent</h3>
    <ul>
    """

    for agent_result in workflow_result.agent_results:
        if agent_result.findings:
            html_body += f"<li><strong>{html_escape(agent_result.agent_name)}:</strong> {len(agent_result.findings)} finding(s)<ul>"
            for finding in agent_result.findings[:5]:
                severity_color = {
                    "critical": "#d32f2f",
                    "high": "#f57c00",
                    "medium": "#fbc02d",
                    "low": "#1976d2",
                    "info": "#455a64",
                }.get(finding.severity.value, "#666")
                html_body += f'<li><span style="color: {severity_color};">•</span> <strong>{html_escape(finding.title)}</strong><br/>'
                if finding.description:
                    html_body += f"<em>{html_escape(finding.description[:100])}</em><br/>"
                html_body += "</li>"
            if len(agent_result.findings) > 5:
                html_body += f"<li>... and {len(agent_result.findings) - 5} more</li>"
            html_body += "</ul></li>"

    html_body += """
    </ul>
    <hr/>
    <p><small>Generated by asdlc</small></p>
    </body>
    </html>
    """

    recipients = [r.strip() for r in settings.email_recipients.split(",")]
    payload = {
        "to": recipients,
        "subject": f"[asdlc] {html_escape(workflow_result.repo_name)} analysis: {total_findings} finding(s)",
        "html": html_body,
    }

    try:
        async with httpx.AsyncClient() as client:
            r = await client.post(
                settings.email_webhook_url,
                json=payload,
                timeout=5.0,
            )
            if r.status_code in (200, 201, 202):
                logger.info(
                    "sent email notification repo=%s recipients=%d findings=%d",
                    workflow_result.repo_name,
                    len(recipients),
                    total_findings,
                )
                return True
            else:
                logger.warning("email send failed status=%d", r.status_code)
                return False
    except Exception as e:
        logger.warning("email notification error: %s", e)
        return False
