#!/usr/bin/env groovy

/**
 * Example Jenkinsfile for asdlc integration
 *
 * This pipeline:
 * 1. Triggers asdlc analysis on code changes
 * 2. Receives findings via webhook callback
 * 3. Publishes findings as JUnit reports and build badges
 */

@Library('asdlc-shared-library') _

pipeline {
    agent any

    environment {
        // asdlc server URL
        ASDLC_URL = credentials('asdlc-server-url')  // e.g., http://localhost:8088
        ASDLC_API_KEY = credentials('asdlc-api-key')

        // Jenkins API token for asdlc to update build status
        JENKINS_API_TOKEN = credentials('jenkins-api-token')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo 'Building...'
                // Your build steps here
                sh 'echo "Build complete"'
            }
        }

        stage('asdlc Analysis') {
            steps {
                script {
                    // Use the shared library to trigger asdlc scan
                    def scanResult = asdlcScan(
                        repo_path: "${WORKSPACE}",
                        branch: "${GIT_BRANCH}",
                        asdlc_url: "${ASDLC_URL}",
                        asdlc_api_key: "${ASDLC_API_KEY}",
                        jenkins_api_token: "${JENKINS_API_TOKEN}"
                    )

                    env.ASDLC_RUN_ID = scanResult.run_id
                    echo "asdlc scan triggered: ${env.ASDLC_RUN_ID}"
                }
            }
        }

        stage('Report') {
            steps {
                script {
                    echo "asdlc analysis run: ${env.ASDLC_RUN_ID}"
                    // Findings will be delivered via webhook callback
                    // and published automatically
                }
            }
        }
    }

    post {
        always {
            // Publish any JUnit reports generated by asdlc callback
            junit testResults: 'asdlc-*.xml', allowEmptyResults: true
        }
    }
}
